### PR TITLE
Replace `getDisplayName` calls with `getName`

### PR DESCRIPTION
**Pull request by BlackBaroness**

### CODE REVIEW

**Comment by VisenP** [comment]
What is the purpose of this, I thought that the display name was replaced with the normal name in PR #2

**Comment by BlackBaroness** [comment]
> What is the purpose of this, I thought that the display name was replaced with the normal name in PR #2

Essentials sometimes calls `Player#getDisplayName` directly, so I used find-and-replace to replace all such calls in commands. But there is no way to check if this `User#getDisplayName` or `Player#getDisplayName` because `User` variable usually named `player`

**Comment by VisenP** [comment]
> > What is the purpose of this, I thought that the display name was replaced with the normal name in PR #2
> 
> Essentials sometimes calls `Player#getDisplayName` directly, so I used find-and-replace to replace all such calls in commands. But there is no way to check if this `User#getDisplayName` or `Player#getDisplayName` because `User` variable usually named `player`

I think it would be good to keep the normal method for the `User` case to keep compatibility with the upstream.

**Comment by BlackBaroness** [comment]
> I think it would be good to keep the normal method for the `User` case to keep compatibility with the upstream.

Well, okay, I reverted it

**Comment by VisenP** [comment]
> > I think it would be good to keep the normal method for the `User` case to keep compatibility with the upstream.
> 
> Well, okay, I reverted it

I think you misunderstood me, I meant that we keep using the getDisplayName method when accessing the name thru the user class but keep it changed(That way we would avoid merge conflicts if those methods are modified by upstream). But it does not matter. Prive wants this to be merged as long as it works.

**Review by VisenP — APPROVED** [review]

**Comment by BlackBaroness** [comment]
> Prive wants this to be merged as long as it works.

I think we should revert reverting then

> I meant that we keep using the getDisplayName method when accessing the name thru the user class but keep it changed(

This is not possible. As I said, there are hundreds of `Player#getDisplayName` calls, and we can't just replace them by converting to `User`. It would be too long

**Comment by privecat** [comment]
Tested & working

**Pull request merged**
